### ISSUE TITLE
project for sagernet

### ISSUE THREAD

**Issue by Mdrzxsony** [ha-ku/what-to-sell-today#495]
@ha-ku 
Hello, you are fine. I wanted you to do a project for me. It is to change the UI and add some features to Sagar Net. I will pay for it .
When editing the source, changes are not made in the emulator, and we had problems even when importing the project
my telegram @mmdrexa_hiis

**Comment by ha-ku** [comment]
> @ha-ku Hello, you are fine. I wanted you to do a project for me. It is to change the UI and add some features to Sagar Net. I will pay for it . When editing the source, changes are not made in the emulator, and we had problems even when importing the project my telegram @mmdrexa_hiis

I must say that I do not fully understand your request after reading. Why do you open an issue about SagerNet (which I think might be the thing you actually talked about) under this repo?
If you really do talk about the SagerNet app, I need to say that I almost know nothing about Android application development. Therefore I'm not able to accept any kind of relevant request. It's not about being paid or not.
